In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv("train.csv",encoding="utf-8")

In [2]:
test = pd.read_csv("test.csv",encoding="utf-8")

In [3]:
df_train = pd.DataFrame(columns=['game_id'])
df_train.game_id = train.game_id.unique()

In [3]:
df_test = pd.DataFrame(columns=['game_id'])
df_test.game_id = test.game_id.unique()

In [4]:
df_train['time'] = np.array(train[train.shift(-1).game_id != train.game_id].time)

In [4]:
df_test['time'] = np.array(test[test.shift(-1).game_id != test.game_id].time)

In [5]:
df = train[train.player==0]
df_train['player0_species']=np.array(df[df.shift(-1).game_id != df.game_id].species)
df = train[train.player==1]
df_train['player1_species']=np.array(df[df.shift(-1).game_id != df.game_id].species)

In [6]:
df_train

       game_id  time player0_species player1_species
0            0  7.24               T               T
1            1  9.59               P               T
2            2  9.59               P               Z
3            3  9.59               T               P
4            4  5.43               T               Z
...        ...   ...             ...             ...
38867    38867  8.22               T               P
38868    38868  9.59               T               P
38869    38869  8.25               P               Z
38870    38870  5.56               P               P
38871    38871  8.52               Z               T

[38872 rows x 4 columns]

In [5]:
df = test[test.player==0]
df_test['player0_species']=np.array(df[df.shift(-1).game_id != df.game_id].species)
df = test[test.player==1]
df_test['player1_species']=np.array(df[df.shift(-1).game_id != df.game_id].species)

In [23]:
df_test

       game_id  time player0_species player1_species
0        38872  7.06               P               P
1        38873  6.07               Z               P
2        38874  4.41               T               T
3        38875  7.58               T               P
4        38876  2.50               Z               Z
...        ...   ...             ...             ...
16782    55654  6.14               Z               T
16783    55655  9.58               Z               T
16784    55656  6.24               P               P
16785    55657  1.17               T               T
16786    55658  4.54               Z               T

[16787 rows x 4 columns]

In [7]:
df = train[train.player==0]
df_train['event_count_0'] = np.array(df.game_id.value_counts()[df.game_id.unique()])
df = train[train.player==1]
df_train['event_count_1'] = np.array(df.game_id.value_counts()[df.game_id.unique()])

In [6]:
df = test[test.player==0]
df_test['event_count_0'] = np.array(df.game_id.value_counts()[df.game_id.unique()])
df = test[test.player==1]
df_test['event_count_1'] = np.array(df.game_id.value_counts()[df.game_id.unique()])

In [8]:
for event in train.event.unique():
    df = train[(train.player==0)&(train.event==event)]
    df = pd.DataFrame(df.game_id.value_counts()[df.game_id.unique()]).rename({'game_id':event+'_count_0'}, axis = 1)
    df['game_id']= np.array(df.index)
    df_train = pd.merge(df_train, df, on='game_id', how='left')

    df = train[(train.player==1)&(train.event==event)]
    df = pd.DataFrame(df.game_id.value_counts()[df.game_id.unique()]).rename({'game_id':event+'_count_1'}, axis = 1)
    df['game_id']= np.array(df.index)
    df_train = pd.merge(df_train, df, on='game_id', how='left')
df_train = df_train.fillna(0)

In [7]:
for event in test.event.unique():
    df = test[(test.player==0)&(test.event==event)]
    df = pd.DataFrame(df.game_id.value_counts()[df.game_id.unique()]).rename({'game_id':event+'_count_0'}, axis = 1)
    df['game_id']= np.array(df.index)
    df_test = pd.merge(df_test, df, on='game_id', how='left')

    df = test[(test.player==1)&(test.event==event)]
    df = pd.DataFrame(df.game_id.value_counts()[df.game_id.unique()]).rename({'game_id':event+'_count_1'}, axis = 1)
    df['game_id']= np.array(df.index)
    df_test = pd.merge(df_test, df, on='game_id', how='left')
df_test = df_test.fillna(0)

In [12]:
df_train

,game_id,time,player0_species,player1_species,event_count_0,event_count_1,Camera_count_0,Camera_count_1,Selection_count_0,Selection_count_1,...,Right Click_count_0,Right Click_count_1,SetControlGroup_count_0,SetControlGroup_count_1,GetControlGroup_count_0,GetControlGroup_count_1,AddToControlGroup_count_0,AddToControlGroup_count_1,ControlGroup_count_0,ControlGroup_count_1
0,0,7.24,T,T,548,548,444.0,425.0,50.0,57.0,...,35.0,28.0,3.0,1.0,24.0,3.0,2.0,0.0,0.0,0.0
1,1,9.59,P,T,1211,1211,627.0,858.0,186.0,116.0,...,160.0,131.0,10.0,8.0,162.0,31.0,1.0,0.0,0.0,0.0
2,2,9.59,P,Z,1371,1371,413.0,725.0,90.0,232.0,...,160.0,204.0,14.0,9.0,99.0,109.0,6.0,5.0,0.0,2.0
3,3,9.59,T,P,1622,1622,713.0,388.0,180.0,148.0,...,276.0,268.0,6.0,19.0,132.0,710.0,0.0,0.0,0.0,0.0
4,4,5.43,T,Z,651,651,430.0,272.0,67.0,126.0,...,177.0,106.0,10.0,8.0,224.0,99.0,1.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38867,38867,8.22,T,P,457,457,639.0,324.0,53.0,58.0,...,95.0,43.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38868,38868,9.59,T,P,776,776,558.0,633.0,62.0,48.0,...,123.0,56.0,0.0,3.0,0.0,8.0,0.0,0.0,0.0,0.0
38869,38869,8.25,P,Z,838,838,785.0,330.0,106.0,191.0,...,248.0,167.0,4.0,6.0,28.0,89.0,0.0,2.0,0.0,0.0
38870,38870,5.56,P,P,593,593,321.0,385.0,24.0,64.0,...,28.0,60.0,1.0,5.0,11.0,43.0,1.0,0.0,0.0,0.0
38871,38871,8.52,Z,T,1491,1491,366.0,584.0,303.0,96.0,...,411.0,313.0,3.0,11.0,435.0,385.0,0.0,0.0,18.0,0.0

In [9]:
for event in train.event.unique():
    df_train['delta_'+event] = df_train[event+'_count_0'] - df_train[event+'_count_1']

In [8]:
for event in test.event.unique():
    df_test['delta_'+event] = df_test[event+'_count_0'] - df_test[event+'_count_1']

In [10]:
df_train

,game_id,time,player0_species,player1_species,event_count_0,event_count_1,Camera_count_0,Camera_count_1,Selection_count_0,Selection_count_1,...,ControlGroup_count_0,ControlGroup_count_1,delta_Camera,delta_Selection,delta_Ability,delta_Right Click,delta_SetControlGroup,delta_GetControlGroup,delta_AddToControlGroup,delta_ControlGroup
0,0,7.24,T,T,592,548,444.0,425.0,50.0,57.0,...,0.0,0.0,19.0,-7.0,0.0,7.0,2.0,21.0,2.0,0.0
1,1,9.59,P,T,1223,1211,627.0,858.0,186.0,116.0,...,0.0,0.0,-231.0,70.0,10.0,29.0,2.0,131.0,1.0,0.0
2,2,9.59,P,Z,851,1371,413.0,725.0,90.0,232.0,...,0.0,2.0,-312.0,-142.0,-16.0,-44.0,5.0,-10.0,1.0,-2.0
3,3,9.59,T,P,1389,1622,713.0,388.0,180.0,148.0,...,0.0,0.0,325.0,32.0,-7.0,8.0,-13.0,-578.0,0.0,0.0
4,4,5.43,T,Z,966,651,430.0,272.0,67.0,126.0,...,0.0,0.0,158.0,-59.0,21.0,71.0,2.0,125.0,-3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38867,38867,8.22,T,P,831,457,639.0,324.0,53.0,58.0,...,0.0,0.0,315.0,-5.0,11.0,52.0,1.0,0.0,0.0,0.0
38868,38868,9.59,T,P,806,776,558.0,633.0,62.0,48.0,...,0.0,0.0,-75.0,14.0,35.0,67.0,-3.0,-8.0,0.0,0.0
38869,38869,8.25,P,Z,1227,838,785.0,330.0,106.0,191.0,...,0.0,0.0,455.0,-85.0,3.0,81.0,-2.0,-61.0,-2.0,0.0
38870,38870,5.56,P,P,406,593,321.0,385.0,24.0,64.0,...,0.0,0.0,-64.0,-40.0,-16.0,-32.0,-4.0,-32.0,1.0,0.0
38871,38871,8.52,Z,T,1617,1491,366.0,584.0,303.0,96.0,...,18.0,0.0,-218.0,207.0,-21.0,98.0,-8.0,50.0,0.0,18.0

In [9]:
df_test

,game_id,time,player0_species,player1_species,event_count_0,event_count_1,Camera_count_0,Camera_count_1,Selection_count_0,Selection_count_1,...,ControlGroup_count_0,ControlGroup_count_1,delta_Camera,delta_Selection,delta_Ability,delta_AddToControlGroup,delta_SetControlGroup,delta_Right Click,delta_GetControlGroup,delta_ControlGroup
0,38872,7.06,P,P,571,715,232.0,467.0,52.0,41.0,...,0.0,0.0,-235.0,11.0,-7.0,-3.0,5.0,119.0,-34.0,0.0
1,38873,6.07,Z,P,421,389,200.0,146.0,114.0,19.0,...,4.0,0.0,54.0,95.0,6.0,-1.0,-5.0,-17.0,-104.0,4.0
2,38874,4.41,T,T,469,824,245.0,220.0,42.0,36.0,...,0.0,0.0,25.0,6.0,4.0,0.0,2.0,-29.0,-363.0,0.0
3,38875,7.58,T,P,1223,863,515.0,357.0,123.0,99.0,...,0.0,0.0,158.0,24.0,37.0,7.0,7.0,-104.0,231.0,0.0
4,38876,2.50,Z,Z,582,213,129.0,161.0,25.0,35.0,...,0.0,0.0,-32.0,-10.0,-1.0,2.0,1.0,23.0,386.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16782,55654,6.14,Z,T,1318,1172,258.0,318.0,186.0,108.0,...,0.0,0.0,-60.0,78.0,-16.0,-13.0,-8.0,-13.0,178.0,0.0
16783,55655,9.58,Z,T,1571,1042,810.0,638.0,317.0,103.0,...,0.0,0.0,172.0,214.0,-13.0,-2.0,7.0,-16.0,167.0,0.0
16784,55656,6.24,P,P,518,697,330.0,328.0,67.0,52.0,...,0.0,2.0,2.0,15.0,-22.0,0.0,1.0,-145.0,-28.0,-2.0
16785,55657,1.17,T,T,42,215,20.0,65.0,5.0,23.0,...,0.0,0.0,-45.0,-18.0,2.0,0.0,1.0,-8.0,-105.0,0.0
16786,55658,4.54,Z,T,189,494,49.0,259.0,73.0,41.0,...,0.0,0.0,-210.0,32.0,-17.0,7.0,-3.0,-109.0,-5.0,0.0

In [11]:
df_train.to_csv("train_base_inform.csv",encoding="utf-8",index=False)

In [10]:
df_test.to_csv("test_base_inform.csv",encoding="utf-8",index=False)